### ISSUE TITLE
Combat simulation seems to think 5 Marauders beat 3 Stalkers and 2 Shield Batteries

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1002]
https://youtu.be/-lw2-AGbp0s?t=913
Should also try to focus the Shield Battery since it has the same amount of health than what it can restore.

**Comment by Unusual229** [comment]
shield batteries can heal each other, no?

**Comment by RaphaelRoyerRivard** [comment]
I thought that they couldn't, but I'm not sure anymore
> The following are not valid targets for healing:
Units or buildings already being healed by another Shield Battery
Units or buildings which have not finished warping in
Units being recalled

**Comment by RaphaelRoyerRivard** [comment]
> bon selon mes tests, les shield batteries ne peuvent pas s'entre healer
Et 4 Marauders vs 3 Stalkers + 1 Shield battery ça le fait pas, peut importe si on target un Stalker ou la Shield battery

**Comment by RaphaelRoyerRivard** [comment]
>mais je viens de tester 5 Marauders vs 3 Stalkers et 2 Shield Batteries, les Marauders perdent s'ils target les Shield Batteries mais gagnent s'ils target les Stalkers (1 Marauder restant)
