### ISSUE TITLE
Mules are supposedly used on empty mineral lines

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1006]
Rasper told us it arrived in that game.
https://ai-arena.net/matches/315921/

**Comment by RaphaelRoyerRivard** [comment]
Yup, we had 3 bases and only the third was not completely depleted and yet we used our Mule in our depleted natural.
![image](https://user-images.githubusercontent.com/5833235/90800124-36513780-e2e2-11ea-933d-dace8511ecf5.png)

**Comment by Unusual229** [comment]
Could not reproduce, however made changes that should prevent our mules from dropping on minerals with less than 225 mineral (I expect its a mineral unit still there but dead at 0 minerals).
