### ISSUE TITLE
3 Marauders think they lose against a Canon and an unpowered one

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1039]
Maybe it's already fixed, but I should still test it.
![image](https://user-images.githubusercontent.com/5833235/94440483-bc795d00-016f-11eb-9d18-ff459e752851.png)

**Comment by Unusual229** [comment]
Can you get the power state of buildings or you have to compute it?

**Comment by RaphaelRoyerRivard** [comment]
Yes we can and I'm already using it pretty much everywhere, but there must be a check missing somewhere.
