### ISSUE TITLE
Replace code that detects cargo return with sc2::IsCarryingMinerals and sc2::IsCarryingVespene

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1049]

**Comment by Unusual229** [comment]
Looked into it. Don't think we will be doing the change.
IsCarryingMinerals doesn't accept const sc2::unit, only sc2::unit, so quite a few things might need to be changed for absolutely no gain, doesn't seem worth it.

**Comment by RaphaelRoyerRivard** [comment]
It accepts a const sc2::Unit &, so when you use it with a unit pointer, you need to dereference it. Also it's not totally useless, since our workers sometimes are used to build stuff while carrying a resource. But it's true that it might not be the priority.

**Comment by Unusual229** [comment]
"our workers sometimes are used to build stuff while carrying a resource" That is unrelated. The code I already have to detect the workers with cargo is perfect.
To confirm this I tried IsCarryingMinerals and IsCarryingVespene, and compared their results to my code result, its identical during the entire game. I will switch my code to use these instead, however it will change nothing in the actual game.

**Comment by RaphaelRoyerRivard** [comment]
Oh ok, I thought it was related. So then it's only missing some checks at a few places.
