### ISSUE TITLE
Cannot take 5th base on GoldenWallLE because of the mineral wall

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1052]
We should use pathfinding to know if we can reach the base. Although, if we do this, sometimes we might not be able to build farther bases because the pathfinding would reach its limit of explored tiles (usually when the worker need to do a big detour).

![image](https://user-images.githubusercontent.com/5833235/95396630-527b5900-08cf-11eb-87ea-2fd24347de94.png)

**Comment by Unusual229** [comment]
Need to be able to mine mineral walls.
If no paths are found to the expand (as I am guessing is currently the case in that situation), we should get if a path can be found if we remove all mineral walls. 
If yes:
we need to figure out which mineral wall to mine (not sure how yet)
If no:
the base is likely an island and we currently don't handle those, but we could make some quick code to not attempt to expand there.

If you have other suggestions, go ahead.
