### ISSUE TITLE
Constructing worker killed during worker rush was never replaced

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1061]
https://aiarena.net/matches/360756/
Even after several minutes, when we weren't under attack anymore, the Barracks never got finished.
![image](https://user-images.githubusercontent.com/5833235/95772453-c3818e80-0c8a-11eb-96fc-a414f7eb983b.png)
In the logs, the Barracks was still in the Building list

**Comment by RaphaelRoyerRivard** [comment]
Happened again against BetterWorkerRush

![image](https://user-images.githubusercontent.com/5833235/96007577-978e1680-0e0c-11eb-9ebf-9a7cbac80c56.png)

**Comment by RaphaelRoyerRivard** [comment]
Happened again https://aiarena.net/matches/366965/

**Comment by Unusual229** [comment]
Worker not replaced is normal. We do not replace workers if there is influence on the way there or at the build location.

**Comment by RaphaelRoyerRivard** [comment]
I guess we should have a parameter (if it does not already exists) that allows the worker to ignore influence. Because it's the only thing that makes us lose against worker rushes at the moment.

**Comment by Unusual229** [comment]
From the last replay, seems like it isn't related to the influence on the barrack.

**Comment by Unusual229** [comment]
Il "build une barrack" depuis 1 minute
![image](https://user-images.githubusercontent.com/8284324/97244053-fd47ae80-17cd-11eb-8f62-5a5fa178e2c7.png)

**Comment by RaphaelRoyerRivard** [comment]
génial

**Comment by Unusual229** [comment]
Added some 'spam' until the worker changes its order, seemed to not change sometime and the worker would keep mining (in the picture above).
