### ISSUE TITLE
Workers are stuck in bunkers

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1100]
https://aiarena.net/matches/379707/
![image](https://user-images.githubusercontent.com/5833235/97893964-efc78280-1cff-11eb-9761-037d910613df.png)
![image](https://user-images.githubusercontent.com/5833235/97893985-f5bd6380-1cff-11eb-8917-654866eb4d8b.png)
![image](https://user-images.githubusercontent.com/5833235/97894013-fce47180-1cff-11eb-85a6-9f384ab7f4ad.png)

They also stack up next to it.
![image](https://user-images.githubusercontent.com/5833235/97894191-3a48ff00-1d00-11eb-95e0-c4a5a777e80a.png)

**Comment by Unusual229** [comment]
Its the issue where too many actions are sent.
