### ISSUE TITLE
Widow Mines should not trigger the anti-invis defense (Engi + Turrets)

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#1117]
At the same time we should check if there are other units that trigger it when it should not .

**Comment by Unusual229** [comment]
Not great if there is a proxy mine drop in our mineral line

We might need two types of triggers.
1- To trigger creation of 'movable' detector (raven, scan, etc) for almost everything that can burrow or cloak
2- To Trigger creation of 'static' detector (turret, cannon, etc) for DT, banshee, ghost, mothership, ...

This way we will still go ahead and try to get a Raven to get the window mine out of there, but avoid spending 275 minerals on trying to build a turret.
