### ISSUE TITLE
Base location tiles are not set properly

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#134]
For a lot of maps, the 2D vector BaseLocationManager::m_tileBaseLocations is wrong.

**Comment by Unusual229** [comment]
Looked at all the maps I locally have :
16BitLE
AcidPlantLE
CatalystLE
DarknessSanctuary
DreamcatcherLE
LostAndFoundLE
MechDepotLE
Redshift

They all look good. Verified with the 'DrawBaseLocationInfo' config option.
