### ISSUE TITLE
Allow resource reservation for an item in the production queue

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#145]

**Comment by Unusual229** [comment]
Donc on réserve les ressources que l'on a besoin pour l'item avec la plus haute priorité dans la queue?
Genre metton qu'on veut jusque un reaper en priorité (50/50), on réserve sa et les autres items de la queue peuvent utiliser les ressources restantes.
Comme on queue presque rien en high priority, sa marche moyen par contre. On a toujours un scv en priorité 2 (plus haut que le default de 0), donc on réserve toujours 50 minerals pour faire un scv. Faudrait voir si sa aide plus que ça peut nuir.

**Comment by RaphaelRoyerRivard** [comment]
Ça devrait être un paramètre quand on l'ajoute à pa queue (reserve resources ou pas). Mais ouin pour l'instant on a pas tant de use cases.

**Comment by Unusual229** [comment]
C'est pushed si tu veut test.

**Comment by Unusual229** [comment]
Sa serait weird d'avoir un truc high priority qui se fait pas parce qu'on a queue un truc moins high priority, mais qui réserve des ressources.

**Comment by Unusual229** [comment]
Je vais close l'issue, on en ouvrira une autre si le besoin se fait sentir.
On réserve les ressources pour toute unit high priority (plus qu'un worker).
