### ISSUE TITLE
Find a way to prevent our units to zigzag

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#222]

**Comment by RaphaelRoyerRivard** [comment]
Could try to average the flee vector and the vector towards the safe tile.

**Comment by RaphaelRoyerRivard** [comment]
Maybe adding a turning cost would help the pathfinding to output a straighter retreat path.

**Comment by Unusual229** [comment]
Didn't you say this was fixed?
