### ISSUE TITLE
Hellions do not back enough when kiting Zealots

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#236]

**Comment by Unusual229** [comment]
We shouldn't make hellions VS protoss, but thats another issue.

**Comment by RaphaelRoyerRivard** [comment]
I think it's necessary against a mass Zealot rush when we only have a
single Barracks and we are not ready to have Banshees yet.

**Comment by Unusual229** [comment]
Cyclone

**Comment by RaphaelRoyerRivard** [comment]
Bon point Jacques faudrait juste les micro comme du monde.
