### ISSUE TITLE
Limit the number of gas workers when low on minerals

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#237]
This could be done in 3 different ways:
- We could just use a worker job ratio but it might not work for every production strategy
- We could start limiting the number of gas worker when we have too much gas (like 200) but it would probably flicker too much
- We could consider what resouce we are missing each frame to create the elements in the production queue and determine the desired worker ratio based on that.

**Comment by Unusual229** [comment]
Sa marche moyen la troisième proposition. Si on voit qu'on manque 5 minerals pour un supply depot, on move des workers du gas vers le mineral, mais la frame d'après on ajoute un Battlecruiser il nous manque 300 gas. On aurait mieu fait de continuer à gather du gas.
C'est un example un peu extrème, mais sa donne l'idée.

**Comment by RaphaelRoyerRivard** [comment]
Ouais ces solutions là ont toutes des défauts

**Comment by Unusual229** [comment]
Faudrait essayer de garder le ratio de 2:1 de starcraft.
Faudrait aussi je regarde les ressources en trop que l'on a à la fin des games.

**Comment by Unusual229** [comment]
Should be maybe fixed.
