### ISSUE TITLE
No more workers are produced at some point

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#238]
In this image, we can see that there is no SCV being produced and there is none in the queue.
![image](https://user-images.githubusercontent.com/5833235/50878937-04a68980-13a7-11e9-9e1e-7fa7f051d23a.png)

**Comment by Unusual229** [comment]
On a un max de 81 workers (27 par bases, avec un max de 3 bases). C'est entièrement normal.

**Comment by RaphaelRoyerRivard** [comment]
Bon point, 81 c'est correct si on réparti correctement les minerals et gas workers, mais présentement ça fait qu'on manque de mineral workers.

**Comment by Unusual229** [comment]
Probablement parce que la main se vide de minerals, mais pas les geysers. Donc on fini avec, metton, 3 base de minerals, mais 4 bases de gas.
Pour fix sa, faut changer les conditions de queue des refinery.

**Comment by RaphaelRoyerRivard** [comment]
Ben cette issue ci c'était pas mal parce qu'on avait atteint le max de workers. On peut fermer l'issue.
