### ISSUE TITLE
SCVs should not repair their resource depot before it is low hp

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#241]
This might have cost us the game against MadBot on the Probots tournament.

**Comment by RaphaelRoyerRivard** [comment]
The repair threshold could be 50% on CC and Orbital but 90% on Planetary.

**Comment by Unusual229** [comment]
Je pense c'est fix, avec le auto repair à 30%, on va le repair quand il est low et la repair station est rendu trop petite pour pogner les depots. À confirmer.

**Comment by Unusual229** [comment]
Will close the issue since I can confirm we repair all buildings that get to low hp.
