### ISSUE TITLE
Reduce the number of repair workers when mineral income is low

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#249]

**Comment by Unusual229** [comment]
On set pu de repair worker quand on a moins de 100 minerals, sa marche ou pas?

**Comment by RaphaelRoyerRivard** [comment]
Ça marche, mais ça serait plus efficace si on pouvait juste mettre moins de
repair workers plus on est pauvre. Parce que des fois on se fait attaquer
early pis on a und banshee qui veut se faire repair mais nos workers font
juste miner alors que si yen avait un ou deux qui iraient la réparer ça
nous aiderait pas mal.
