### ISSUE TITLE
The wall's supply depots are lowering even if enemy units are near

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#250]

**Comment by Unusual229** [comment]
Si l'enemis est far enough, on descend le supply depot. Je peux simplement augmenter le range. On veut pas raise le wall au complet, comme sa les units enemy glitch à essayer de passer. Ils voient un trou et essait d'y aller au lieu d'être bloqué et attacker le wall.

**Comment by Unusual229** [comment]
Increased by 25%

**Comment by RaphaelRoyerRivard** [comment]
Ohh brillant
