### ISSUE TITLE
The production manager crashed (nothing was built after 6 min)

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#251]
It happed in our game against Tyr on the Probots tournament.

**Comment by Unusual229** [comment]
Un vrai crash ou tu penses que c'est un crash?

**Comment by RaphaelRoyerRivard** [comment]
Le bug semble s'est reproduit dans cette game là.

2019-01-16 21:37:25 | CheeZerg | Zerg | CeruleanFallLE | Win | 3 | Replay | 00:16:54 | 78.796303
