### ISSUE TITLE
Detect range upgrades

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#252]
Mainly against missile turrets, but if general enough, could be used to detect range upgrades on hydralisks and other units if there are some.

**Comment by RaphaelRoyerRivard** [comment]
We could monitor the hp of our units, like it is done for invis detection. When one of our units takes damage while being on a tile with no influence and its last action is a move command, we could check some closeby units and determine the probable cause of the hp loss. It is likely that this would only detect the missile turrets range upgrade and not for the range upgrade of other units, because their influence range is increased based on their movement speed. But this could also be used to detect cloaked units.

**Comment by Unusual229** [comment]
Smart, sa pourrait remplacer le code lent de détection de unit invisible (qui run pas présentement..).
Tu peux déjà faire sa, utilise CombatAnalyzer, il contient tout les UnitStates. Si tu checks le UnitStates d'une unit, tu peux savoir si elle a prit du dommage durant la dernière frame et checker ton influence map si c'est le cas.
Si jamais tu as des falses positives, peut-être que c'est mieu d'assumer que l'ennemis à l'upgrade de range, à toi de voir.
