### ISSUE TITLE
The supply depots of the wall get lowered, allowing enemies to pass through

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#257]

**Comment by Unusual229** [comment]
Sa arrive tu encores? J'avais increase le raise radius, ya un pti bout.

**Comment by RaphaelRoyerRivard** [comment]
Ça l'air bien maintenant. Le problème est plus de mon côté, faudrait je code dequoi qui s'assure que nos units ne s'arrêtent pas sur les lowered supply depots. Sauf que ça sera pas évident...

**Comment by RaphaelRoyerRivard** [comment]
J'va closer l'issue pis si jamais je vois que ça arrive trop souvent (ça fait un bout que ça m'est pas arrivé), je vais en créer une nouvelle.
