### ISSUE TITLE
Cancel construction of attacked building under construction when low hp to get a refund

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#262]
Check if hp of building is lowering on several frames.

**Comment by RaphaelRoyerRivard** [comment]
We could also do the same for a finished building that is producing a unit so we get the refund of that unit.

**Comment by Unusual229** [comment]
Doesn't matter. You are refunded the unit anyway.

**Comment by RaphaelRoyerRivard** [comment]
Pas mal sûr que non

**Comment by RaphaelRoyerRivard** [comment]
Ah ok tu parlais d'une unit en production (je voyais pas mon commentaire précédent par courriel)

**Comment by Unusual229** [comment]
This could be abused to win against us. A light push on the expansion when it starts building would cost us 400 minerals and, probably, the game. Will mark as important.

**Comment by Unusual229** [comment]
We cancel if the DPS ( - building health gain by being built) in the last second is twice or above the remaining HP. We might need to increase to x3 or something else if we still lose buildings sometimes.
