### ISSUE TITLE
The list of buildings under construction shows buildings that are not under construction

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#266]
This probably happens when we are losing a building that is under construction or when we lose an SCV that is moving towards the location where it wants to build the building. When it happens with a CC, the game is almost automatically a lose.

**Comment by Unusual229** [comment]
Sa tu dis que sa arrive encore, même avec le fix que j'avais fais?

**Comment by RaphaelRoyerRivard** [comment]
Ouais ça arrive contre OneTrickPony, je me souviens avoir vu des Refinery
dans la liste, faudrait je recheck pour voir si ça le fait avec d'autres
buildings.

Raphaël Royer-Rivard


Le dim. 10 févr. 2019 à 16:12, Unusual229 <notifications@github.com> a
écrit :

**Comment by RaphaelRoyerRivard** [comment]
Je confirme, ça vient de me le faire après avoir perdu 2 refinery et le commandcenter de la third, le bot réserve les resources pour 2 refinery alors qu'il n'est pas prêt à aller les construire.
Ensuite une fois qu'on reprend la base (genre 3-4 minutes plus tard), on build les refinery et ça enlève les buildings de la liste.
![image](https://user-images.githubusercontent.com/5833235/52539844-da9f0900-2d50-11e9-9102-5f38d5ecabdb.png)

**Comment by Unusual229** [comment]
Donc c'est un bug qui se fix tout seul?

**Comment by Unusual229** [comment]
Si oui, enlève le tag "Important".

**Comment by RaphaelRoyerRivard** [comment]
Well, c'est vrai que c'est rendu moins pire qu'avant, mais ça fait quand même que quand on perd une base, on se freeze 150 minerals (2 refinery) pour rien dans un moment où notre income diminue parce qu'on se fait attaquer.

**Comment by Unusual229** [comment]
Sa arrive tu encore? Moi sa me dit fuck all.

**Comment by RaphaelRoyerRivard** [comment]
Juste pour les refineries des bases qu'on perd, on les met dans la liste
alors qu'on est pas prêt à les faire. Le reste tu l'as fix.
