### ISSUE TITLE
Cannot expand when next expansion location is taken by the enemy

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#269]

**Comment by Unusual229** [comment]
Tes 100% certain sa arrive? Parce que j'ai check le code pi les conditions sont correct. Si  c'est le cas, sa veut dire faut je fix la détection des bases ennemies.

**Comment by RaphaelRoyerRivard** [comment]
Pour tester tu peux compiler notre bot en mettant en commentaire la
création de units pis tu fais jouer notre bot contre lui même.
