### ISSUE TITLE
Workers try to build the next expansion even on creep

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#271]
If there is already a check, maybe the creep appeared after the check was done.

![image](https://user-images.githubusercontent.com/5833235/52459580-0beebd80-2b34-11e9-845d-040c8ae7aabf.png)

**Comment by Unusual229** [comment]
À chaque tick de "lowPriorityCheck" je check si ya un building qui est planifié sur du creep, si oui, je le cancel.

**Comment by RaphaelRoyerRivard** [comment]
C'est nouveau ou c'est ce que t'avais déjà codé et tu comprends pas
pourquoi ça arrive quand même?

**Comment by Unusual229** [comment]
C'est sa je vien de push :)

**Comment by Unusual229** [comment]
NOTE: Pas testé avec du creep, je les juste testé manuellement dans VS.

**Comment by RaphaelRoyerRivard** [comment]
Ok faque faudra faire une autre issue pour décider de la prochaine base
location dans le cas où on peut pas build à celle qu'on a prévu?
