### ISSUE TITLE
Occupied builders are sometimes selected to build a new building

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#273]

**Comment by Unusual229** [comment]
Tes certains? Je peux rajouter une boucle sur tout les buildings en cour et checker si le worker je veux assigner est assigné à un building en cour.
Le problème c'est que c'est pas un truc que je peux tester.

**Comment by RaphaelRoyerRivard** [comment]
Sur à 100%, si on pouvait uploader des replays dans les issues je l'aurais fait mais on peut pas. C'est effectivement pas facile à tester, ça arrive juste de temps en temps.

**Comment by Unusual229** [comment]
Should be fixed, need to keep an eye out for the issue.
Remember to pull!
