### ISSUE TITLE
Reduce the number of calls to Util::PathFinding::IsPathToGoalSafe()

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#274]

**Comment by Unusual229** [comment]
Pas possible.
Si tu veux que je fasse les checks pour pas perdre de worker, c'est nécessaire. J'en fait juste un par movement de worker, c'était-à-dire au début pour savoir si je peux faire le movement ou pas.
Le mieu que je peux faire, mais sa va affecter la qualité de bot, c'est mettre des trucs dans "lowPriorityChecks".

**Comment by RaphaelRoyerRivard** [comment]
Je pensais à plutôt mettre un cooldown sur le call de la méthode lorsqu'elle retourne false. Tu pourrais avoir un map de unit et de long qui garde en mémoire c'est quand la dernière requête échouée faite pour un worker pis ne faire la requête que si le worker n'est pas dans le map ou si la frame (long) du dernier échec date d'il y a plus de 1 sec genre.

**Comment by Unusual229** [comment]
On peut aussi faire que la map est pas par tile, plutôt en 2x2 ou 3x3 tiles. Sa réduirait énormement le coût en performance.

**Comment by RaphaelRoyerRivard** [comment]
Je peux coder la réduction des calls (genre si la méthode retourne false,
on recheck pas avant 1s plus tard).

**Comment by Unusual229** [comment]
1s c'est long

**Comment by RaphaelRoyerRivard** [comment]
Pas tant que ça, dans la micro de combat c'est une pause de 2s quand on
trouve pas de path.

**Comment by RaphaelRoyerRivard** [comment]
J'ai fait que chaque worker a un cooldown de 1 sec après un échec (peu importe sa destination). Si tu trouves que ça parait visuellement que c'est pas optimal, on ajustera.

**Comment by Unusual229** [comment]
Fix le fait que c'est just selon la unit. Sa doit considérer la unit et le position en même temps.

**Comment by RaphaelRoyerRivard** [comment]
Done. Faut garder un oeil voir si tout se passe bien

**Comment by RaphaelRoyerRivard** [comment]
Ça reste lent dans WorkerManager::lowPriorityChecks() quand on se met à avoir plein de workers (genre un lag de 1 sec, c'est vraiment bad).

**Comment by Unusual229** [comment]
Sa doit juste lagger quand on fait un gros worker transfer, right?

**Comment by RaphaelRoyerRivard** [comment]
non ça laggait très fréquemment en fin de game, probablement parce qu'on avait un surplus de workers dans toutes les bases donc à chaque fois que ça passant dans lowPriorityChecks ça faisait plein de calls au PathFinding

**Comment by RaphaelRoyerRivard** [comment]
Tu devrais faire qu'on essaie pas de transferer des workers si toutes les bases sont saturées. Ça devrait réduire le nombre de call.

**Comment by Unusual229** [comment]
Est-ce que le problème exist encore?

**Comment by RaphaelRoyerRivard** [comment]
J'ai pas testé ce que t'as push pendant je dormais faque je sais pas. Faudrait faire des tests.

**Comment by Unusual229** [comment]
Reduced the number of calls again (when doing the premovement). We should be good now, right?

**Comment by Unusual229** [comment]
Closing the issue, unless theres an opposing comment.

**Comment by RaphaelRoyerRivard** [comment]
This isn't an opposing comment.
