### ISSUE TITLE
Workers are stuck between building things and harvesting gas

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#282]
All the workers are flickering, unable to move. The number of workers per refinery changes each frame and the building 'shadows' are appearing and disappearing every frame.
It happened to me with a low count of workers (like 3-4), but I don't know if it can happen with more workers.

**Comment by Unusual229** [comment]
Peut-être fixed? J'ai fix une coup de cas qui font sa, mais peut-être qu'il en reste.

**Comment by Unusual229** [comment]
J'ai pushed un genre de fix. J'ai arrêté de checker la différence entre le nombre de mineral et gas workers, on check juste si on a pas gros de mineral worker et selon nos ressources. Sa devrait éviter beaucoup de gas -> mineral -> gas loop. Je close pas l'issue tout de suite, jveux tu me dis si ta eu d'autre problème ou non.

**Comment by RaphaelRoyerRivard** [comment]
Je crois que ton fix fait en sorte que si ça détecte ce problème là, ça cancel le building et ça en repart un nouveau, c'est possible? Parce que le wall ne se finit pas toujours maintenant.

**Comment by Unusual229** [comment]
Le wall ne fini pas parce que quelque chose tuer un worker. Si sa arrive, on fini pas le wall. Si on essait de finir le wall non-stop, on suicider nos worker si ya un truc enemy. Présentement, je crois qu'un enemy sur la ramp va cancel le supply depot, je peux faire qu'on le cancel pas, mais on le delay à quand sa sera safe.

**Comment by RaphaelRoyerRivard** [comment]
Oui le délayer c'est ce qui faut.

**Comment by Unusual229** [comment]
J'ai close ton issue qui est un duplicate de celle-ci. On build le supply depot ailleur si ya une threat sur la ramp, prochaine fois qu'on build un supply depot (et que y'a pas de threat) on va le build à la ramp.
