### ISSUE TITLE
No move SCV are produced after being wiped out

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#284]
Ça arrive probablement juste avec certaines conditions précises, parce que ça faisait vraiment longtemps j'avais pas vu ça.
![image](https://user-images.githubusercontent.com/5833235/52545485-e527c580-2d85-11e9-82fc-873148770b43.png)

**Comment by RaphaelRoyerRivard** [comment]
Ok c'est parce que ya un Orbital Command dans la liste de production. Il faudrait avoir une meilleure condition (genre si on a moins de X workers, on devrait pas s'empêcher d'en créer).

**Comment by RaphaelRoyerRivard** [comment]
Lorsqu'on vient de démarrer un nouveau CC (ou qu'on a un nouveau CC complété?), on ajoute le Orbital Command dans la liste de production. Si on perd notre CC avant d'avoir pu démarrer l'Orbital Command, ça va rester dans la liste alors il faudrait soit avoir une condition de création de worker qui n'est pas empêché par un Orbital Command ou qu'on enlève le Orbital Command de la liste de production si on a pas de CC complété.

**Comment by Unusual229** [comment]
Ou queue l'orbital quand on a un CC (pas orbital ni plantery).
Je pourrais également faire qu'un CC va pas queue de worker si l'on a une barrack. Sa veut dire qu'il va faire le orbital si yen a un de queue et que les orbitals peuveut continuer à faire des workers. Le problème c'est si on a un CC et que le orbital est pas queue (pour peu importe la raison), le CC fera pu rien. Donc faudrait peut-être plutôt ne plus queue de orbital et plutôt donner l'ordre de faire un orbital au CC, quand on peut. Sa devrait fix le problème.

**Comment by RaphaelRoyerRivard** [comment]
Je crois pas qu'on devrait empêcher un CC de faire des SCV si on a une
barracks, il faudrait aussi lui permettre d'en faire quand on a pas de cash
et pas de workers (sinon c'est long en criss attendre d'avoir assez pour
upgrader).

**Comment by Unusual229** [comment]
Sa va être plus compliqué que prévu, étant donné qu'il faut aussi permettre de faire la Planetary.

**Comment by Unusual229** [comment]
J'ai deux options de fix :
#1 On set la priorité du orbital plus haut que le worker. Il peut arriver qu'un worker soit construit avant que le orbital soit queue (semble être 25% du temps?). PAR CONTRE, sa n'arrivera avec AllowDebug à false, puisque "putImportantBuildOrderItemsInQueue" va run à chaque frame au lieu de chaque 10 frames. Pas besoin de nouveau code.
#2 On check le nombre de worker avant de queue un worker sur un command center, si on en a plus que X on bloque les workers pour forcer l'orbital. Par contre, sa fait plus de code et de condition.

Les deux options marchent bien pour la planetary.
Dit moi celle que tu préfères.

**Comment by RaphaelRoyerRivard** [comment]
La première solution a l'air suffisante

**Comment by Unusual229** [comment]
Good, c'est vraiment le plus simple.
Ya pas de risque de causer d'autre bug aussi.
