### ISSUE TITLE
Finish the wall later when there is danger

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#286]
Je ne sais pas trop pourquoi, mais ça arrive environ 1 game sur 3 ou 4 selon mes tests. Parfois il ne manque qu'un seul depot, des fois 2.

**Comment by RaphaelRoyerRivard** [comment]
Par exemple, un reaper enemy passe proche de notre rampe, on ne veut donc pas aller build le supply depot près de lui. On fait donc le 3e supply depot près de notre CC. Le 4e pourrait finir le wall.

**Comment by Unusual229** [comment]
Sa m'a fourrer en criss que l'issue a disparru.
C'est fait.
