### ISSUE TITLE
Improve the worker defense logic

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#287]
1. Workers should use the effects influence map to flee danger zones, like a nuke strike or a corrosive bile.
2. Workers should flee instead of fight when there are too many enemies or when enemies have AOE attacks (like banelings, hellions/hellbats, tanks, etc.).
3. Otherwise, workers should attack close enemies.

**Comment by Unusual229** [comment]
if(we have no fighting unit)
  //On attack si on a pas de unit, parce que les units partiront pas par magie
  //Faudrait peut-être checker nos buildings voir si un reaper/banshee va sorir par contre
  Attack
else

int AllyTotal = worker.count * 50;
const float ratio = 2.5f;

foreach enemy
  //pondère la puissance de l'enemy à sa vie, permet d'avoir moins peur de zergling bas en vie
  EnemyTotal = (enemy.mineral + enemy.gas) * enemy.HP%
  
//Si le puissance estimé de l'armé enemy est plus basse que notre puissance estimé, Attack
if(EnemyTotal * ratio < AllyTotal)
  Attack
else
  Flee

**Comment by Unusual229** [comment]
Tu peux peut-être réutiliser ton code qui calcule la puissance des armées et juste buff la puissance de l'armé enemy  par rapport à nos workers.
