### ISSUE TITLE
Purification Novas (Disruptor's attack) should be in the effect influence maps

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#294]

**Comment by Unusual229** [comment]
It is in the other influence map, correct?
Just making sure we react to Disruptors even if its in the wrong influence map.

**Comment by RaphaelRoyerRivard** [comment]
I've never seen a disruptor in one of our games so I don't even know what is the unit it spawns. My guess is that it spawns a unit that has no weapon so it would be invisible in every influence map.

**Comment by RaphaelRoyerRivard** [comment]
Easily testable with cheats though.

**Comment by RaphaelRoyerRivard** [comment]
The unit has the `PROTOSS_DISRUPTORPHASED` type and has no weapon. I should prevent our units from targetting it and add a ground effect on the influence map.
