### ISSUE TITLE
Refineries should not reserve resources if they are located on a base that has no resource depot

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#296]

**Comment by Unusual229** [comment]
(pour moi)
Download/Acid_Plant_LE_62.SC2Replay

**Comment by Unusual229** [comment]
Issue might be fixed.
Before reserving resources and moving the buildings from the queue to in-production, we check if the path is safe.
Will leave open until it is confirmed fixed.

**Comment by Unusual229** [comment]
Might be able to reduce the number of calls to IsPathToGoalSafe, should check 'getProducer'.

**Comment by RaphaelRoyerRivard** [comment]
Je pense que ça fonctionne, en tout cas on ne réserve plus les ressources pour les refineries et je peux voir le CC dans la queue (de production, pas la liste en train d'être build). Mais ça lag pas mal et vu qu'on ne réduit pas notre production, on n'arrive pas à avoir assez de mineral pour rebuild le CC (si on veut régler ça, ça serait dans une autre issue).

**Comment by Unusual229** [comment]
Bug is fixed
