### ISSUE TITLE
Update sc2client-proto

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#297]

**Comment by Unusual229** [comment]
Should wait until we have access to the invisible units or any other important change.

**Comment by RaphaelRoyerRivard** [comment]
The IDs have changed, we should create scripts similar to those:
https://github.com/Dentosal/python-sc2/blob/master/generate_id_constants_from_stableid.py 
https://github.com/Dentosal/python-sc2/blob/master/generate_id_constants.py
