### ISSUE TITLE
Do not mine with mule if it is dying soon

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#301]

**Comment by Unusual229** [comment]
Was going to do some complicated maths to determine if the Mule could successfully do another trip, but there is a better solution. The answer is 9. The mule can do 9 successful harvest and mine for a 10th harvest, but will die before returning the minerals. After 9 trips, the mule should be send to the enemy base as a way to scout whats close to the base.

**Comment by Unusual229** [comment]
https://liquipedia.net/starcraft2/MULE_(Legacy_of_the_Void)

**Comment by Unusual229** [comment]
The 10th harvest issue only happens when the mules is sent to the closest mineral patch, which is always is right now. That means that every mule is wasting 25 minerals we could have harvested.

**Comment by Unusual229** [comment]
Mule should also be sent at the furthest mineral patch. This will reduce our mineral income very slightly, there might be a 0.5 second extra delay between the mule's 25 minerals income, but it will also make it so the bases will have an higher average income, when the back mineral fields start to empty before the front mineral fields. Also, mules will still gather the exact same amount of minerals, just delayed a little.

**Comment by Unusual229** [comment]
Should not drop a mule on a mineral patch with less than 250 minerals?
