### ISSUE TITLE
Prioritize big mineral shards on expansions with mules

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#302]

**Comment by Unusual229** [comment]
This might be a different issue, but I will list it here for now and see if some can be done at the same time or not.
- Prioritize the latest expansion to use mules on, maximum of 1 per patch (need to keep track of mules alive).

**Comment by Unusual229** [comment]
Did not do whats in comment, created an issue instead.
