### ISSUE TITLE
getBuildLocationNear is slow

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#311]
Happens only when it get called often, like when a building is retried every frame because it is located at a place with enemy influence. It probably lags because it calls `canBuildHereWithSpace` which calls `buildable` which calls `m_bot.Map().canBuildTypeAtPosition` which issue a placement query to the game.

![image](https://user-images.githubusercontent.com/5833235/54251400-7d4bd280-451d-11e9-9adb-f5d86cf2cf18.png)

**Comment by Unusual229** [comment]
Might be better with the addition of the influence map check, which I just pushed.
I haven't validated whether it helps or not yet.

**Comment by Unusual229** [comment]
Should be fixed, since I optimised it quite a bit and removed all queries.
