### ISSUE TITLE
Produce Ravens based on meaningful conditions

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#312]

**Comment by Unusual229** [comment]
"meaningful conditions" which are not included :)
For now, it will probably be like 1 raven per 5 or 10 flying units, round up, starting after 2 banshees.
This issue as simple as a if statement in the production manager, since we already have all the requirements for the Raven, from the Banshees.

**Comment by Unusual229** [comment]
I will not do this issue until the Raven is moderately well micro, use cheats to spawn yourself some ravens. When this becomes important so you can test in real games, let me know.

**Comment by Unusual229** [comment]
When getting the count of raven, we can't check the number of raven in production. GetUnitCountByType with Completed = false, might be only for buildings.

**Comment by Unusual229** [comment]
For now, the "meaningful conditions" will be if we don't have a raven and none in production. Might add a condition to make sure we have at least 2 banshees first, but it might not be needed since it costs a lot of gas, it might work on its own.
