### ISSUE TITLE
Dummy issue for Alexis

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#313]

**Comment by Unusual229** [comment]
Build barrack in wall:
The middle depot should be a barrack, whether we want an addon or not. When its time for the addon, the barrack should lift and build the addon. A supply depot should be built where the barrack once was. This will allow for a faster walling.

**Comment by RaphaelRoyerRivard** [comment]
If we want to do that against Protoss, we'll need a better worker micro against worker rush (do exactly like VeTerran).

**Comment by Unusual229** [comment]
Why would we require better micro?

**Comment by RaphaelRoyerRivard** [comment]
Because we'll lose the worker building the Barracks and will never be able
to complete it.

**Comment by RaphaelRoyerRivard** [comment]
With better micro, we could send the workers to defend at the ramp and
repair them while they fight.

**Comment by Unusual229** [comment]
NEW ISSUE:
[Macro] Optimize First frame worker split, workers should be sent to mine in the order of the furthest from any minerals.

**Comment by Unusual229** [comment]
NEW ISSUE:
[Macro] Improve performances. A lot of things are called every frame, but could, perhaps, be called every frame, but only when needed. An example would be the worker transfer. We check if we need to transfer every 10 frames, but really, we could check every time we create a worker, a CC or a worker finishes a building. I am sure that if we look, we could find things that are called often for no real reason, both in Macro and Micro.

**Comment by Unusual229** [comment]
NEW ISSUE:
[Macro] Cancel unit in production if there is a unit that is queued as high priority and the unit in production is not high priority and is barely started (10% or less?).
