### ISSUE TITLE
Allow units to launch opportunistic attacks

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#315]
If not in enemy influence, our units should be able to attack a target in range as soon as their attack is not in cooldown even though they have a different primary target.

**Comment by Unusual229** [comment]
UnusualToday at 11:37 PM
Faut tu fasses attention par contre, ya des targets tellement prioritaire que perdre du temps à attacker un autre truc, c'est bad.

RaphRRToday at 11:37 PM
ouais j'va juste le faire si notre target prioritaire est relativement loin
