### ISSUE TITLE
Improve worker premovement

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#316]

**Comment by Unusual229** [comment]
If heavy on performance, add a check to avoid checking the distance if we don't have like 50-75% of the ressources

**Comment by RaphaelRoyerRivard** [comment]
You could use the Util::DistSq * 1.x to have a rough estimate and use the
precise distance with pathfinding only when you almost have the resources
for that distance.

**Comment by Unusual229** [comment]
Not a bad idea.

To have the Tile/Second of worker, check CCBot :
"Le calcul est fait dans CCBot pour détecter les speedlings"

**Comment by Unusual229** [comment]
const float mineralRate = m_bot.Observation()->GetScore().score_details.collection_rate_minerals;

**Comment by Unusual229** [comment]
Raph's method to check the distance will return 0 if the path isn't safe. No call to IsPathToGoalSafe required.
