### ISSUE TITLE
Move back injured units when fighting threats

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#317]
Only when attack is on cooldown and keep it in attack range of its target.

**Comment by Unusual229** [comment]
[12:36 AM]
Unusual:
	Est-ce que tu concidère le temps pour que la unit tourne? Sa va changer gros l'efficacité.

[12:36 AM]
BlindMidget:
	Non, je sais pas si j'ai cette info là

[12:37 AM]
Unusual:
	Si tu concière pas le turn, la unit risque d'attaquer moins souvant que normalement.
