### ISSUE TITLE
Do not apply premovement to CC

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#331]

**Comment by RaphaelRoyerRivard** [comment]
EJK seems to think that our expansion timings were good, so when we'll be able to have a large army composition and take good army decision (like build up an army instead of streaming units onto the enemy base), we should remove the patch that prevents the premovement on expansions. That is only if we scout that the enemy is not so dangerous at that time.

**Comment by Unusual229** [comment]
Added the info in a TODO, so we can remove it when needed.
