### ISSUE TITLE
Separate influence maps based on if the influence comes from ground or air

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#339]
We would then have 6 influence maps:

- Enemy power on ground from ground
- Enemy power on ground from air
- Enemy power in air from ground
- Enemy power in air from air
- Effect on ground
- Effect on air

**Comment by Unusual229** [comment]
The advantage is that we could allow ground units to enter ground influence to attack ground units, while avoiding ground influence caused by air units.

**Comment by RaphaelRoyerRivard** [comment]
But if there is a stalker and a void ray, the workers might get into the
range of the stalker because they want to attack it but never be able to go
near enough to land a hit because they'd be afraid of the void ray's
influence.

I think for the moment I'll just make them flee from air influence if they
have no target.

**Comment by Unusual229** [comment]
You need to check if the unit (worker in this case) advances to attack an enemy, will it be in range of an undesired enemy influence. It can get rather complicated I believe.
