### ISSUE TITLE
Prevent stuck units

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#342]
Since we only check if the tiles below buildings are not reserved (doesn't matter if they are walkable), units get can stuck in ledges.

**Comment by Unusual229** [comment]
Check if a potentially stuck unit can go to either the middle of the map or the main base.

**Comment by Unusual229** [comment]
Bump

**Comment by Unusual229** [comment]
The solution could be to have separate maps for the reserved tiles for building and for tiles we don't want to build on to prevent stuck units (walk only tiles).

Reserved tiles cannot be build on by any other building than what we originally wanted to build there (current behavior).
Tiles to prevent stuck units can be built on, but only by supply depots.

This would allow us to have walk only tiles around barrack/factory/starport/armories/engeering bay to be 100% sure we never have stuck units, but still build supply depots in between, so we don't have to split our main on multiple bases.

**Comment by Unusual229** [comment]
The planed changes will cause issues when trying to build walls with something else than supply depots (or offensive buildings). Might also cause issues when trying to build behind the mineral line, since the building required space is "bigger". If it is problematic, we can add an argument that skips some checks, however it would mean units could be stuck again.

**Comment by RaphaelRoyerRivard** [comment]
We definitely need something to ignore those changes for putting the Barracks in the wall. As for building behind the mineral line, we'll have to test if there's enough space but we definitely have to not ignore your changes there as it is the most frequent situation that cause a stuck worker. Also, will it apply to the Missile Turrets in the mineral line? Because sometimes worker get stuck between it and some mineral patches, but there are not much space.

**Comment by Unusual229** [comment]
It wouldn't fix the turret issue in the mineral line. If you know a specific map where a worker could be stuck, I'll try applying this fix to the mineral turret as well and see where it ends up being placed instead.

**Comment by RaphaelRoyerRivard** [comment]
It doesn't happen reliably on specific maps, I think it sometimes change the position of the Turret if it failed to build it too many times because a worker was in the way and then it makes it too close to the mineral patch and only sometimes get stuck.

**Comment by Unusual229** [comment]
The turret never changes position (or at least it shouldn't).

**Comment by RaphaelRoyerRivard** [comment]
Ok then maybe it happens only on specfic maps, but it's been a while since I've seen the problem happen so I'll keep an eye open.

**Comment by Unusual229** [comment]
I would expect it to be map specific and "luck" based, since the worker exits the building at a random location.
If it blocks the path to a mineral patch, it might be better for the economy to move the turret too, so that could be a win-win situation.

**Comment by Unusual229** [comment]
Didn't fix the turret part, but still closing since it is part of another issue.
