### ISSUE TITLE
Prioritize latest expensions for mules

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#343]
Prioritize the latest expansion to use mules on, maximum of 1 per patch (need to keep track of mules alive).

**Comment by Unusual229** [comment]
I confirm that mules to block other mule, like workers do to each other.

**Comment by Unusual229** [comment]
Should have a list of bases to drop mules on. This will allow to always drop on largest mineral fields, instead of closest, when a base is mined out.
We should go through the list in reverse order, to prioritize the most recent expends. If there is more mules to drop than available bases, we go through the list again.

**Comment by RaphaelRoyerRivard** [comment]
Also make sure the base on which the Mule is dropped is not under attack.

**Comment by Unusual229** [comment]
We never check that :)

**Comment by Unusual229** [comment]
The check was added, since I was already doing stuff in that code. Did not work on this issue however.
