### ISSUE TITLE
Buildings are not always repaired

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#347]
![image](https://user-images.githubusercontent.com/5833235/55210057-0fa9d280-51bc-11e9-8920-07198cf72502.png)

**Comment by Unusual229** [comment]
Didn't find any issue in the code.
I reduced the conditions to allow to repair with less minerals, also improved performances.

**Comment by Unusual229** [comment]
Might be related to enemy influence (isPathSafeToGoal).

**Comment by Unusual229** [comment]
Buildings are rarely repaired.
For the image above, it might be another bug where influence from enemies is left behind even once the unit is dead. Not 100% sure the bug does exists, check https://github.com/RaphaelRoyerRivard/MicroMachine/issues/351 for info.

**Comment by Unusual229** [comment]
We only repair from 30% and down (raised it at 50%)
We also require at least 15 minerals. Not sure what happened in the image above.

**Comment by Unusual229** [comment]
Does not repair if the path isn't safe (except for planetary, bunker and turrets).

**Comment by Unusual229** [comment]
Closing this one since we have a more recent issue for the same problem.
