### ISSUE TITLE
Heavy lag when trying to transfer workers

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#351]
If an enemy attacks our base, it seems to leave influence after the death of the units. When we try to transfer workers, it checks isPathSafeToGoal and fails for every worker transfer. (Micro)

To improve performance, could check to transfer from a base to another, which would allow to not do the check for every single workers. (Macro).

**Comment by Unusual229** [comment]
To reproduce the issue, start a game vs an AI at 1 and set the bot to produce no units. Make sure you have 6 bases at least (create some manually). Then wait to be attacked. Once the attack is killed by our workers, it should start lagging heavily every 2 in-game seconds.

**Comment by RaphaelRoyerRivard** [comment]
What do you mean by it seems to leave influence? Have you checked with the debug display?

**Comment by Unusual229** [comment]
I haven't, but isPathSafeToGoal was saying it wasn't safe, even though there wasn't a single visible enemy in the whole map. it lastest for a few minutes, then I stopped the test. Was playing without units against level 1 AI.

**Comment by Unusual229** [comment]
Will try to reproduce on my side, while testing other stuff at the same time.

**Comment by Unusual229** [comment]
Dont recall seeing this issue again. Closing.
