### ISSUE TITLE
Base under attack are not always detected

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#358]
![image](https://user-images.githubusercontent.com/8284324/55530058-6018a880-5672-11e9-90cb-ea999ce0ab5a.png)

**Comment by Unusual229** [comment]
Not sure whether its Macro, micro or both.

**Comment by RaphaelRoyerRivard** [comment]
How do you know it is not under attack?

**Comment by Unusual229** [comment]
SCVs didn't defend the base.

**Comment by Unusual229** [comment]
SCV don't defend this far. Since we usually have units, I guess its fine.
