### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#374]
Probably missing a delete somewhere.

**Comment by Unusual229** [comment]
I found a total of 2 or 3 " new " in the code.
I am thinking it might be not a memory leak, maybe its just that our bot never forgets any units it saw, even when its dead. So overtime the memory increases.

**Comment by RaphaelRoyerRivard** [comment]
It might be caused by collections never being cleared.
