### ISSUE TITLE
Ravens should not try to drop their turret on enemies

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#381]
Since ground units that do not attack air are not threats to the Raven, we don't have a good "nearby enemy units" list. We should then check all the enemy units to make sure there is none that blocks the auto-turret.

**Comment by Unusual229** [comment]
Could be part of the canBuildHere method (or which ever one you use). Would prevent us from trying to build buildings on enemy workers (does not fix workers blocking expands). If you do modify the method, you probably want to add a bool to disable that check.

**Comment by RaphaelRoyerRivard** [comment]
My snippet is hardcoded for a building size (we cannot know its size without already having it). Anyway, if we check the influence map, we shouldn't need to check the enemy units.
