### ISSUE TITLE
Consider turn delay when attacking

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#382]
There seems to be no way of knowing the turn speed of units...

**Comment by RaphaelRoyerRivard** [comment]
Increase attack duration by 2 frames for large angles and 1 frame for medium angles.

**Comment by Unusual229** [comment]
Turn rate is probably linked to the unit speed.

**Comment by Unusual229** [comment]
Best way to know it, would be to figure out the maths. Could record at 60 fps a few units doing 180 and see how many frames it takes. Then do ratio between the frames to turn and the unit speed. I expect this would give similar results for each units.

constant = frames to turn / speed

**Comment by RaphaelRoyerRivard** [comment]
It seemed to work well for all units with 0-2 frames of delay depending on
the angle, but it might be too much for units that are fast. I don't think
I am willing to perform a throughout test on it since we have a lot of more
important matters to deal with atm.
