### ISSUE TITLE
Test ProBots maps

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#400]
Acropolis LE
Thunderbird LE
Cyber Forest LE
Kairos Junction LE
King's Cove LE
New Repugnancy LE

**Comment by RaphaelRoyerRivard** [comment]
The maps pool has been updated.
Cyber Forest
Kairos Junction
King's Cove
New Repugnancy

**Comment by Unusual229** [comment]
All the above maps + those 4?

**Comment by RaphaelRoyerRivard** [comment]
They are the same, but with 2 removed.

**Comment by Unusual229** [comment]
RIP didn't realised 👍

**Comment by RaphaelRoyerRivard** [comment]
The new maps are downloadable here (Ladder 2019 Season 1)
https://github.com/Blizzard/s2client-proto#map-packs
password is "iagreetotheeula"

**Comment by Unusual229** [comment]
Only New Repugnancy left to test. I will test it and add all maps to the random map list.
