### ISSUE TITLE
Take new bases slowly

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#406]
1 was left unfinished, 2 were in construction while 1 had nearly no worker.

![image](https://user-images.githubusercontent.com/5833235/58771954-e3784c80-8584-11e9-84cf-954b853e9f0a.png)

**Comment by Unusual229** [comment]
Probably not going to change anything for this. We expand when we have the resources to do it. If we were producing Marines at the same time as Battle cruisers, it would force us to expand slower.

**Comment by RaphaelRoyerRivard** [comment]
Maybe I could try to add code for production of Marines and their objective location would be to follow Battlecruisers so they don't end up by themselves.

**Comment by Unusual229** [comment]
Even if we have a bunch of marines running around the map, its not that bad. Could catch a few overlords, maybe find and attack expands, both options are viable.
