### ISSUE TITLE
Improve Cyclone production logic

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#407]
Prevent production of Cyclones when there are many zerglings and produce more Cyclones when there are many Mutalisks.

**Comment by Unusual229** [comment]
Can't be done by the tournament.
Will probably be forced to create a map of which unit counter which unit. Then I can consider the enemy army and pick direct counters to it. Micro could probably use something like this too. The drawback is that we will have to keep it updated ourselves, but I don't see any other realist option.

**Comment by RaphaelRoyerRivard** [comment]
I'll just add some hardcoded conditions for the moment, like it is done with Hellions.

**Comment by Unusual229** [comment]
Bad, but yeah. Will replace all that one day.
