### ISSUE TITLE
Also produce Marines when producing Battlecruisers

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#409]
Should have more than 1 Barracks, but should not have too many, otherwise we won't have enough minerals to produce more Battlecruisers.

The Marines should wait until they are enough and then go support the Battlecruisers.

**Comment by Unusual229** [comment]
You don't want to queue Marines if you do not have enough mineral for the next Battlecruiser, so it can be started immediately. Up to you to check if we should reserve 400 minerals per starport building BC or just 400. You build a new barrack if you would queue a Marine, but all of them are busy and we have 550 minerals.

Also it might cause us to expand just as much if you do the above, will discuss.
