### ISSUE TITLE
Workers are Idle when they shouldn't

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#412]
Ya plein de Idle workers...
Les autres bases en avaient 8.
![image](https://user-images.githubusercontent.com/5833235/59004207-e5d9e100-87e6-11e9-9801-3efbc5408ded.png)

**Comment by RaphaelRoyerRivard** [comment]
Pis ya pas d'indice dans les logs à part que ça spam
```
7080: [ERROR] : Invalid build location for TERRAN_REFINERY | 0x0000002```

**Comment by Unusual229** [comment]
Supposé être fix, si tu l'as pas revu, close sa.
