### ISSUE TITLE
Invalid repair stations with low worker count

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#413]
Injured units think that a low mineral worker base is not a repair station anymore right when mineral workers become repair workers.

**Comment by RaphaelRoyerRivard** [comment]
We could probably also count the number of repair workers instead of only mineral workers.

**Comment by Unusual229** [comment]
Ton fix marche pas?

**Comment by RaphaelRoyerRivard** [comment]
J'en ai pas encore fait, pis j'avais close l'issue sans faire exprès.

**Comment by Unusual229** [comment]
Oh lol alright

**Comment by Unusual229** [comment]
fixed
