### ISSUE TITLE
Buildings are not repaired

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#415]
![image](https://user-images.githubusercontent.com/5833235/59049630-68e65000-8856-11e9-8681-a49a3a5a2f4d.png)

**Comment by RaphaelRoyerRivard** [comment]
Might be related to the fact that we are low on minerals. If it is the case, we might want to ignore that condition when our buildings are burning.

**Comment by Unusual229** [comment]
I am unsure whats the minimal amount of minerals we want to start repairing, we would have to check in the code.
Should be easy to do an exception for burning buildings, but if we are really low on minerals, we might not be able to repair it at all.

**Comment by Unusual229** [comment]
Did you see this issue happen again?

**Comment by RaphaelRoyerRivard** [comment]
Not recently

**Comment by Unusual229** [comment]
No mention of this bug since June, Closing.
