### ISSUE TITLE
Production buildings are idle even when we have enough resources

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#416]
We can't even create army units because the 400 minerals for new bases are reserved while we have almost no minerals...

![image](https://user-images.githubusercontent.com/5833235/59050412-45bca000-8858-11e9-9474-1b40acbb0d75.png)

**Comment by Unusual229** [comment]
On réserve juste quand on atteint 400 minerals, on réserve pas d'avance. Va juste falloir une condition pour les battlecruisers.

**Comment by RaphaelRoyerRivard** [comment]
As-tu au moins regardé le screenshot? On a plein de gas mais on produit absolument rien parce qu'on a réservé des minerals pour faire un expand alors qu'on en avait pas.

**Comment by Unusual229** [comment]
On avait 481 minerals, normal qu'on commence un expand. Le problème c'est pas sa, c'est qu'on produit rien.
c'est un duplicate de sa : https://github.com/RaphaelRoyerRivard/MicroMachine/issues/391

**Comment by RaphaelRoyerRivard** [comment]
On avait pas 481 minerals, les minerals sont encore reserved, check le debug display.

**Comment by RaphaelRoyerRivard** [comment]
Et c'est pas un duplicate, on est pas rendu à faire des BC, le screenshot a été pris à 6:02. À ce moment là on est sensé faire des Banshees (quand on est pas à -400 minerals).

**Comment by Unusual229** [comment]
Peux pas confirmer, mais le point vert à gauche dans la map, moi je pense que c'est un worker qui va build un expand. Si c'est sa, alors on a 481 minerals. Quand tu donnes l'ordre de build, sa fait une ombre vert et sa enlève les ressources, donner une autre ordre redonne les ressources, donc on a belle et bien 481 minerals. On réserve juste les ressources pour un CC si on a un 400 minerals de free, sa peut bloquer un BC, mais sa devrait pas blocker une banshee.

**Comment by Unusual229** [comment]
Removing the High priority flag could help, currently it means that even ever we have 400 minerals, we will build a CC and not check the other options. Issue with this is, we might never get to expand, not sure.

**Comment by RaphaelRoyerRivard** [comment]
J'pense t'as raison pour le worker qui s'en va build la prochaine base, j'avais pas réalisé que ça enlevait les minerals même avant de commencer à build. Dans ce cas là le problème c'est vraiment que les buildings ne produisent pas de unit, comme tu disais.
Et je crois pas que ya un problème avec la priorité parce que les bases sont ajoutées comme priorité basse.

**Comment by Unusual229** [comment]
Oh, je pensais que c'était High priority.
Dans se cas là, faut trouver pourquoi on produisait rien.

**Comment by Unusual229** [comment]
On a 81 minerals, on peut rien produire avec sa, sauf un worker, mais sa c'est une autre issue.
