### ISSUE TITLE
King's Cove map has 2 bases too close to each other

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#417]
![image](https://user-images.githubusercontent.com/5833235/59051582-38ed7b80-885b-11e9-8045-b9d1bbd9d403.png)

**Comment by Unusual229** [comment]
Thats intended. If we keep moving worker between bases to keep the numbers even, our economy will be garbage.

**Comment by Unusual229** [comment]
So the issue isn't that its not "evenly" split, its that its not splitting.
We keep workers equal or lower to the number of mineral patch * 3, so in this screenshot, we would keep workers up to 24. Could go higher if the bot thinks a workers is mining is X base, but is actually mining in base Y, rare but happens. If it does get to 30+, then there might be another issue.

**Comment by Unusual229** [comment]
proof
![image](https://user-images.githubusercontent.com/8284324/59153598-f1b5e500-8a2a-11e9-9f64-23e28900619a.png)

**Comment by Unusual229** [comment]
Issue is that the distance is calculated with DistSq instead of ground distance.

I cannot change the checked distance because, although it does fix this issue, lowering it by a single tile prevents some geysers from being detected properly.

**Comment by Unusual229** [comment]
Only these manager's "onStart" is called before we need to calculate the ground distance, anything inside another manager is not usable.

m_techTree.onStart();
m_strategy.onStart();
m_map.onStart();
m_unitInfo.onStart();

**Comment by Unusual229** [comment]
Some mineral field are not detected as part of a cluster.
![image](https://user-images.githubusercontent.com/8284324/59169131-ec2dcd00-8b06-11e9-98ba-4dbdf2d18aee.png)

**Comment by Unusual229** [comment]
![image](https://user-images.githubusercontent.com/8284324/59169150-036cba80-8b07-11e9-958f-717a0b58f1be.png)

**Comment by RaphaelRoyerRivard** [comment]
The reason for which the minerals aren't added to the cluster is because they are not on the same terrain height...
![image](https://user-images.githubusercontent.com/5833235/59234580-7172b980-8bbb-11e9-972b-3f853d419cbc.png)

**Comment by RaphaelRoyerRivard** [comment]
Fixed on Probots maps
