### ISSUE TITLE
Natural is flagged as blocked when there is nothing on Kings Cove

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#418]
![image](https://user-images.githubusercontent.com/5833235/59051688-76ea9f80-885b-11e9-8a98-f5f90681920d.png)

**Comment by RaphaelRoyerRivard** [comment]
Also happens with a bunch of other expands.
After 15 mins, a worker built a CC in the natural even if it was still flagged as blocked.

**Comment by Unusual229** [comment]
We are only supposed to flag as blocked when we fail to build there and all flags are cleared once we succesfully build an expand. Something weird is happening.

**Comment by RaphaelRoyerRivard** [comment]
Yeah, it becomes blocked as soon as it wants to expand, even though we do not have vision on the natural.

**Comment by Unusual229** [comment]
Eh... is the white circle supposed to be where the expand goes?

**Comment by RaphaelRoyerRivard** [comment]
No, it's the center of the Clear Expand squad.
