### ISSUE TITLE
No building is built after 5:30

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#421]
![image](https://user-images.githubusercontent.com/5833235/59323533-056e7f00-8ca9-11e9-92ab-57e77eb953d2.png)

**Comment by RaphaelRoyerRivard** [comment]
Also, no new expands are built...

**Comment by RaphaelRoyerRivard** [comment]
No clue found in logs and doesn't happen in Debug against in-game AI...

**Comment by RaphaelRoyerRivard** [comment]
Might not be related, but in the replay, I saw that it started to spam the location error of refineries right when it wanted to build refineries in the third even though it wasn't finished.
![image](https://user-images.githubusercontent.com/5833235/59402904-6d3acd80-8d6e-11e9-9c77-d38c58f7d344.png)

**Comment by RaphaelRoyerRivard** [comment]
I wasn't reading the right log file, so I just found these:
```
6780: BuildingManager::assignWorkerToUnassignedBuilding | Path to TERRAN_COMMANDCENTER isn't safe
...
6958: BuildingManager::assignWorkerToUnassignedBuilding | Path to TERRAN_COMMANDCENTER isn't safe
7129: BuildingManager::assignWorkerToUnassignedBuilding | Path to TERRAN_REFINERY isn't safe
```
There was no threat in our base and both command centers were in construction, so no need to assign a new worker to it...
And for the unsafe path to the refinery, I don't know why, maybe it took a worker that was on top of a building and it failed to find a path because it couldn't even move 1 space.
Nothing explains why no building were built after 5:30...

**Comment by Unusual229** [comment]
Maybe the geyser is somehow part of another base after your change? Not sure if it happened before or after though.

**Comment by RaphaelRoyerRivard** [comment]
It happened after, but I checked the debug display for all the bases and they were fine. I'll recheck to make sure though.

**Comment by RaphaelRoyerRivard** [comment]
Also in the first screenshot, we can see that the worker's lowPriorityChecks takes a lot of time, this might be a clue to identify the problem. Unfortunately, there was nothing in the logs at this point...
