### ISSUE TITLE
Builders are idle when they wait to have enough resources to go build their building

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#429]
Happens for every buildings, even the first refineries

**Comment by Unusual229** [comment]
??? in debug anyway, its pretty much always instant.
How much waiting is there?

**Comment by RaphaelRoyerRivard** [comment]
Around 3-4 seconds for the second refinery, can't tell for the first or the barracks

**Comment by RaphaelRoyerRivard** [comment]
And it doesn't seem to happen to me neither in local. Only on the ladder...

**Comment by Unusual229** [comment]
Happens for the 2nd refinery for sure.
