### ISSUE TITLE
Often more than one worker are chosen to build a refinery

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#440]
Sometimes it's not only 2, but 3.
![image](https://user-images.githubusercontent.com/5833235/59967849-50389400-94fe-11e9-8066-7510733362f5.png)

**Comment by Unusual229** [comment]
Did a fix for this, saw it happen at least once. Seems to happen less often at least.

**Comment by Unusual229** [comment]
Didn't see the issue in a while, closing.
