### ISSUE TITLE
The second refinery is built only when we have 150 mineral

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#466]
There seems to be a bug with reserved resources for refineries.

**Comment by Unusual229** [comment]
Tested in Debug (without getting latest), works perfectly fine.
![image](https://user-images.githubusercontent.com/8284324/60763711-275ce680-a048-11e9-9269-3dd1e8504386.png)

**Comment by Unusual229** [comment]
Both geysers at 0:58, without waiting extra time.

**Comment by RaphaelRoyerRivard** [comment]
Wtf

**Comment by Unusual229** [comment]
Just so we are on the same page, the two initial refineries are part of the BO and completely ignore the reserved resources.

**Comment by Unusual229** [comment]
Will need more info so I can repro the issue.

**Comment by RaphaelRoyerRivard** [comment]
Indeed, I'll take a screenshot next time to see what really happens.

**Comment by RaphaelRoyerRivard** [comment]
Nevermind, it's because we often start a worker at the same moment.
![image](https://user-images.githubusercontent.com/5833235/60764225-b4f20380-a053-11e9-87d0-0904f64538f1.png)
