### ISSUE TITLE
Tiles are associated to the wrong bases

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#468]
On Treachery
![image](https://user-images.githubusercontent.com/5833235/60855353-50f54980-a1d1-11e9-8c33-099126318145.png)

**Comment by Unusual229** [comment]
faudrait que je change la logique, j'imagine sa ressemble à

Foreach base
foreach tile
if in range
reserve it

pour

foreach tile
getClosestBase
if in range
reserve it

**Comment by Unusual229** [comment]
Tested a few maps, always looked perfect to me.
Not sure which maps are in the tournement, I could validate those specifically.

**Comment by RaphaelRoyerRivard** [comment]
The maps listed in "RamdomMaps" are the ones in the map pool for the
tournament. I've put the others in another list.
