### ISSUE TITLE
Production buildings with Reactors are not prioritized when building a low tech unit

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#487]
When producing a Viking while having a Starport with Reactor and a Starport with Techlab, the Viking will always (from what I've seen) be produced by the Starport with Techlab.

**Comment by Unusual229** [comment]
Works perfectly fine on my side, for both Reapers and Vikings.
Will prioritize Reactors, but will build on TechLab if there is no Reactors available.

**Comment by Unusual229** [comment]
Unless you can reproduce the issue, I'll close it.
