### ISSUE TITLE
Placement is wrong on Cyber Forest LE

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#490]
During the ProBots quarter final, the Starport was placed in a spot where it couldn't make its Reactor.
![image](https://user-images.githubusercontent.com/5833235/61995280-3ede2c80-b054-11e9-8f6e-f26cd1d2dab4.png)

**Comment by Unusual229** [comment]
Duplicate of https://github.com/RaphaelRoyerRivard/MicroMachine/issues/522
