### ISSUE TITLE
Production buildings should be produced instead of taking all the bases

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#492]
It isn't right to take all the bases in the map while having only a limited amount of production buildings. During the quarter finals of ProBots, if we had more production buildings instead of bases, we might had enough to fight back.
![image](https://user-images.githubusercontent.com/5833235/61995359-81eccf80-b055-11e9-8da3-58db766937aa.png)

**Comment by RaphaelRoyerRivard** [comment]
This line should probably be revised because it often limits our production (sometimes there is a bug and we can't expand more, and sometimes we already took all the bases)

```
if (hasPicked && !m_queue.contains(toBuild) && !m_queue.contains(MetaTypeEnum::CommandCenter))

**Comment by Unusual229** [comment]
Right, can fix this rather easily.

**Comment by Unusual229** [comment]
&& (!m_queue.contains(MetaTypeEnum::CommandCenter || minerals > 400 || HasNoBasesLeft))
Sa couvre tout les cas je pense?

**Comment by RaphaelRoyerRivard** [comment]
Ça me semble bien


Le mer. 25 sept. 2019 à 11:24, Unusual229 <notifications@github.com> a
écrit :
