### ISSUE TITLE
Test how many Vikings it takes to beat Tempests

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#493]
Spawn Vikings against AP and see how many it takes to beat different numbers of Tempests. An Observer should also be spawn on the Vikings.

**Comment by Unusual229** [comment]
In the lastest patch (as of 11/30/2019), 2 vikings kill 1 tempest with 1 viking at full health. This is assuming both sides have 0 upgrades. Also assumed both sides do focus firing.

Heres the results of a few tests: 

2v - 1t -> 1v (100% hp)
4v - 2t -> 3v (78% hp)
3v - 2t -> 1v (80% hp)

However upgrades favors Tempest majorly.
If both sides are 3-3:
3v - 2t -> 1t (100% hp, 75% shield)
4v - 2t -> 2v(75% hp)
Note that 4v - 2t is 100 more minerals for Terran, but 50 less gas. So we can see it has similar costs.
20v - 10t -> 13v(?% hp)

All the above tests are in the optimal scenario where there is not a single stalker.
10v - 3t & 5s -> 1t & 5s

In optimal situations, Vikings trade well versus Tempest, but stalkers counter Vikings very very hard.

**Comment by Unusual229** [comment]
If you need more info or want to test this yourself, let me know.

**Comment by RaphaelRoyerRivard** [comment]
As tu testé avec des Tempests statiques? Parce qu'en réalité les Tempests kitent.

**Comment by Unusual229** [comment]
Statique, qui kite sa sera pas aussi facile a tester.

**Comment by RaphaelRoyerRivard** [comment]
Faudrait tester plutôt contre AdditionalPylons en spawnant des Vikings et Tempests.
