### ISSUE TITLE
Wall sometimes stops after the first depot

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#511]
Sometimes, when trying to build the second wall depot, the worker will try to go build it at the right place (we see the green hologram) but will instead build it next to the CC.

![image](https://user-images.githubusercontent.com/5833235/64579468-08811600-d351-11e9-906d-34ab16218bb9.png)

**Comment by Unusual229** [comment]
Should be fixed by my recent fix.
