### ISSUE TITLE
Proxy worker is dancing instead of walking towards building location

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#542]
When using correctly the `canMakeAtArrival` method (by setting the `finalPosition` of the building), the proxy worker is chosen at the right moment (when it is walking back to base) but instead of walking directly towards the proxy location, it moves back and forth for several seconds.

**Comment by Unusual229** [comment]
Setting finalPosition??
The proper way to build exactly where you want is to add a nextBuildingLocation. Check out how the wall does it.
