### ISSUE TITLE
Mules are not always requested on minerals

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#579]
![image](https://user-images.githubusercontent.com/5833235/68889926-e9558a80-06eb-11ea-9cfb-b1be60c4de3e.png)

**Comment by Unusual229** [comment]
In BuildingManager castBuildingsAbilities::1690

Replace:
auto point = closestMineral->pos;

//Get the middle point. Then the middle point of the middle point, then again... so we get a point at 7/8 of the way to the mineral from the Orbital command.
point.x = (point.x + (point.x + (point.x + orbitalPosition.x) / 2) / 2) / 2;
point.y = (point.y + (point.y + (point.y + orbitalPosition.y) / 2) / 2) / 2;
Micro::SmartAbility(b.getUnitPtr(), sc2::ABILITY_ID::EFFECT_CALLDOWNMULE, point, m_bot);

With:
Micro::SmartAbility(b.getUnitPtr(), sc2::ABILITY_ID::EFFECT_CALLDOWNMULE, closestMineral->pos, m_bot);

**Comment by Unusual229** [comment]
Waiting for the league and AIArena to be using the version of Starcraft 2 that supports dropping mules on the mineral directly.
