### ISSUE TITLE
No repositioning is done when an enemy unit is blocking a production building location

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#583]
For example, a location is chosen for the proxy Barracks but a Probe is already there, blocking the location. Our SCV will keep trying to build the Barracks there.

**Comment by RaphaelRoyerRivard** [comment]
Example
![image](https://user-images.githubusercontent.com/5833235/69908108-e5df2600-13b0-11ea-9057-4f93efaa044e.png)

**Comment by Unusual229** [comment]
Needs to be retested, but I am pretty sure it is fixed now.

**Comment by Unusual229** [comment]
This should be fixed. Didn't see it happen since. Closing.
