### ISSUE TITLE
No Starport is built

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#588]
Happened in this game
https://ai-arena.net/matches/67912/
![image](https://user-images.githubusercontent.com/5833235/69497445-2ae3f380-0eab-11ea-931c-9e793bdf9ad9.png)

**Comment by Unusual229** [comment]
Do we know if there was any glitched workers?

**Comment by RaphaelRoyerRivard** [comment]
Also happened in https://ai-arena.net/matches/71768/
