### ISSUE TITLE
Buildings in a blocked expansion are not cleared

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#589]
Happened in this game
https://ai-arena.net/matches/67914/
![image](https://user-images.githubusercontent.com/5833235/69497573-9bd7db00-0eac-11ea-9828-ab03fc077661.png)

**Comment by Unusual229** [comment]
If it can help, I don't thing it is flagged as blocked. The cannon is technically not in the way.
