### ISSUE TITLE
Resource depots are not always repaired

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#593]
![image](https://user-images.githubusercontent.com/5833235/69591442-c5822680-0fc0-11ea-9b5c-a6a4c691cee7.png)

**Comment by RaphaelRoyerRivard** [comment]
Also happened in this game
https://ai-arena.net/matches/1178/

**Comment by RaphaelRoyerRivard** [comment]
Still happens
https://ai-arena.net/matches/167730/
![image](https://user-images.githubusercontent.com/5833235/77781358-cfc63700-702b-11ea-9220-6181ce32ac7d.png)

**Comment by Unusual229** [comment]
Still happens?

**Comment by RaphaelRoyerRivard** [comment]
I think so, but it does not happen often because usually we lose our base when we get attacked. And it seems to happen only on long games so it is very hard to reproduce.

**Comment by Unusual229** [comment]
I set the command center, orbital and both of their flying variant, as targets to repair, even if the path to them isn't safe. The maximum repairer is 3 (based on the building health %). If this is acceptable, I will commit and put a "Keep an eye out" tag on this issue.

**Comment by RaphaelRoyerRivard** [comment]
Hmm I am not sure it would work well in all cases. Let's say we lost all the workers of our expansion so we start pulling the ones from our main to repair the base and lose them one after the other.

Maybe we should still check if the path is safe unless the worker is already near.

**Comment by Unusual229** [comment]
I need to validate, but I am pretty sure I only try to use the workers already in that base.

**Comment by Unusual229** [comment]
I can confirm I was wrong and will change it so it uses only workers in that base.

**Comment by Unusual229** [comment]
Fixed. However, gas workers currently cannot repair depots, only mineral workers.
