### ISSUE TITLE
Do not research BansheeCloak if rushed

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#613]
https://ai-arena.net/matches/4463/
![image](https://user-images.githubusercontent.com/5833235/70293271-3c33d680-17ae-11ea-89cf-5ec3a4a75807.png)

**Comment by Unusual229** [comment]
Do we currently have a clear definition of when we are being rushed?
Is it still stuff like flagging we are rushed when there are X enemy workers in our base?

**Comment by RaphaelRoyerRivard** [comment]
We have 2 kinds of rush definition, worker rush and early rush (I think it's before 3 min from units other than workers).
