### ISSUE TITLE
Nearly all the workers from every base got sent to build a refinery of a new expansion location

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#627]
They were all blocking themselve so it never got built.
https://ai-arena.net/matches/10347/

![image](https://user-images.githubusercontent.com/5833235/70579670-55a69b00-1b7f-11ea-8d17-44dcd834b617.png)

![image](https://user-images.githubusercontent.com/5833235/70579695-635c2080-1b7f-11ea-88cc-0b99409491b0.png)

**Comment by RaphaelRoyerRivard** [comment]
Also, nothing else was built after that.

**Comment by RaphaelRoyerRivard** [comment]
And workers stopped building...
![image](https://user-images.githubusercontent.com/5833235/70579884-e67d7680-1b7f-11ea-9312-6a9b97027f41.png)

**Comment by Unusual229** [comment]
Had this happen to me (after some changes), I did a fix for it and haven't seen it happen again. Its in the same commit as my fix for the building placement (canBuildHere, buildable and stuff)

**Comment by Unusual229** [comment]
Didnt see this issue since January. Closing.
