### ISSUE TITLE
Addons should not be rebuilt right away when there are enemy units nearby

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#656]
We lost/canceled our techlab like 100 times.
https://ai-arena.net/matches/32122/
![image](https://user-images.githubusercontent.com/5833235/71481971-296d5a00-27ce-11ea-863b-5a5ca51de9ae.png)

**Comment by Unusual229** [comment]
Made it so addon are not built at all when enemies are close by (Combat Influence) so it shouldn't include workers, right? If so, the issue can be closed.

**Comment by RaphaelRoyerRivard** [comment]
Workers also generate influence, so it would probably wait sometimes where we would still want to create the addon. I think the best would be to have a addon creation cooldown for every Barracks, Factory and Starport.

**Comment by Unusual229** [comment]
???

**Comment by Unusual229** [comment]
Now only rebuild if the influence is too high. (5 and 10 influence, depending on the addon)
