### ISSUE TITLE
Loads of resources of reserved for building new expansions, preventing us from producing any unit

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#660]
https://ai-arena.net/matches/32962/
While constructing the first expand, we got to 400 minerals, triggering a new expansion...
![image](https://user-images.githubusercontent.com/5833235/71524846-4ae94700-289d-11ea-9fd5-cbdc19dff065.png)
And then the proxy worker got chosen to produce the second Starport... And while we had the resources for upgrading the first expansion, resources were seemingly reserved for something else...
![image](https://user-images.githubusercontent.com/5833235/71524656-6ef85880-289c-11ea-978e-005eef48a49e.png)
We went on 4 bases with nearly no army supply...
![image](https://user-images.githubusercontent.com/5833235/71524717-cb5b7800-289c-11ea-9a9f-98685030115b.png)

**Comment by Unusual229** [comment]
Would change this to be an improvement and be "Expanding should be based on our army supply and (maybe) known enemy supply".
