### ISSUE TITLE
BarracksTechLabs are listed twice in the "under production" list

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#662]
When debugging, I found out they were twice in BuildingManager::m_buildings

**Comment by Unusual229** [comment]
Does it affect anything?

**Comment by RaphaelRoyerRivard** [comment]
It did forced me to code a workaround once. It was when I was counting the number of add-on we had, the number was off by 1 because of this bug.
