### ISSUE TITLE
Buildings are built in proxy location instead of main base

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#666]
![image](https://user-images.githubusercontent.com/5833235/71697727-f0615680-2d86-11ea-86db-6aceb3084de0.png)

**Comment by Unusual229** [comment]
Depuis quand?
Est-ce toujours comme ca?
Ladder ou non?

Je n'es pas changer le code pour le placement des buildings quand on proxy, uniquement quand on est rushed (et c'est dernière notre mineral, pas a la proxy), alors je ne sais pas quel est le problème. Il n'est pas arrivé durant mes tests pour l'instant.

**Comment by RaphaelRoyerRivard** [comment]
Depuis que j'ai merge tes changements. J'ai pas encore vu ça arriver contre l'AI. Tu peux spawn des ennemis dans notre proxy ou jouer zerg contre pour essayer de proc avec des zerglings.

**Comment by RaphaelRoyerRivard** [comment]
La Factory a été built dans notre first alors qu'on s'est jamais fait attaqué...
![image](https://user-images.githubusercontent.com/5833235/71768439-f6207e80-2ee3-11ea-92b1-9a359b9afead.png)
