### ISSUE TITLE
Too many workers are sent to repair the wall's buildings

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#669]
We should choose a number of repair workers depending on the health percentage of the building.
![image](https://user-images.githubusercontent.com/5833235/71700021-60c0a580-2d90-11ea-9c31-99158c40017c.png)

**Comment by Unusual229** [comment]
Limit was 5, changed to 1. Can easily be changed to something else.

**Comment by Unusual229** [comment]
search and modify "maxWallRaparator"

**Comment by RaphaelRoyerRivard** [comment]
That shouldn't be the solution

**Comment by Unusual229** [comment]
Hadnt seen the comment. Now depends on building health, up to 5 workers max.
