### ISSUE TITLE
Starport was misplaced

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#675]
Starport was placed right next to a supply depot, thus preventing it from creating an addon.
![image](https://user-images.githubusercontent.com/5833235/71784973-132e7d80-2fc8-11ea-84fb-5054c87f8f07.png)

**Comment by Unusual229** [comment]
si ta le nom de la map et le BO, je peux peut-être le reproduire

**Comment by RaphaelRoyerRivard** [comment]
https://ai-arena.net/matches/46150/
ThunderbirdLE
Early expand

Est-ce que t'as fix le bug qui fait qu'on construit nos building dans notre dernière base même si ya juste notre proxy qui se fait attaquer?

**Comment by Unusual229** [comment]
Oui, faut que je le unfix pour que la repro marche?

**Comment by RaphaelRoyerRivard** [comment]
I guess, c'est la seule fois j'ai vu ce bug là. On peut attendre que ça se reproduise sinon

**Comment by Unusual229** [comment]
Got this specific case happening, both the starport and depot were started nearly at the same time. So somehow which ever building was ordered second didn't see the first one was blocking.
Could be because they are ordered at the same frame, but very unlikely.

**Comment by Unusual229** [comment]
Should be fixed, didn't happen in a while. Closing.
