### ISSUE TITLE
A worker tries to build a Supply Depot on a Starport (heavily supply blocked)

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#679]
https://ai-arena.net/matches/47654/
![image](https://user-images.githubusercontent.com/5833235/71831924-dde16880-3077-11ea-90cf-d25e0a206431.png)

**Comment by RaphaelRoyerRivard** [comment]
Also happened here
https://ai-arena.net/matches/47668/
![image](https://user-images.githubusercontent.com/5833235/71833531-1afb2a00-307b-11ea-84f1-d7f996f6d3e3.png)

**Comment by Unusual229** [comment]
Didnt happen in over a month. Closing.
