### ISSUE TITLE
Supply depots are built behind our mineral lines instead of in the wall

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#681]
No enemy units were in our base, but our proxy was under attack.
https://ai-arena.net/matches/49764/
![image](https://user-images.githubusercontent.com/5833235/71939525-fd17ed00-3180-11ea-9d01-62a4464498d1.png)

**Comment by Unusual229** [comment]
Note: Related to the proxy being worker rushed or something like that. Triggers the code that tells us to build behind the mineral line for safety.

**Comment by Unusual229** [comment]
Any clue if it still happens?

**Comment by RaphaelRoyerRivard** [comment]
Haven't seen it in a while
