### ISSUE TITLE
We stop producing Marauders after losing the proxy Barracks

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#706]
https://ai-arena.net/matches/65648/
![image](https://user-images.githubusercontent.com/5833235/72689378-c629cb80-3ade-11ea-8656-1973ac6d58a8.png)

**Comment by Unusual229** [comment]
Did it happen again?

**Comment by RaphaelRoyerRivard** [comment]
I think it was because it triggered the end of the proxy Marauders strat and Marauders were produced only with that strat active. It shouldn't be a problem anymore if we always produce Marauders against mass Stalkers.
