### ISSUE TITLE
Limit the number of Reapers produced

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#733]
After 5 minutes, we were still producing Reapers. This cost us too much gas, so we had to wait until past 7 mins to have the cloak upgrade.
![image](https://user-images.githubusercontent.com/5833235/73962878-3c02a500-48dd-11ea-92a3-08f80cf6b091.png)

**Comment by Unusual229** [comment]
On limite les reapers déjà selon leur dmg dealt/received. Mais si tu veux un truc static genre pu de reaper passé X minutes ou pu de reaper quand on a un starport, on peut.

**Comment by RaphaelRoyerRivard** [comment]
J'pense que la limite de dmg dealt/received c'est pas assez vu qu'ils ont fait pas mal de damage au début mais après 3-4 minutes ils servaient pu à rien. On pourrait arrêter d'en produire quand on en a plus que 1 dès qu'on a une Factory complétée selon moi.

**Comment by Unusual229** [comment]
We stop producing reapers once we have a factory (or if we have 0 reapers). We should use a marine to scout instead of a reaper, but thats a different story.
