### ISSUE TITLE
3 Barracks were built for proxy Marauders build

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#750]
https://ai-arena.net/matches/109289/
![image](https://user-images.githubusercontent.com/5833235/74888097-0634d600-534b-11ea-93d8-0e8402229608.png)

**Comment by Unusual229** [comment]
With the Marine strategy, I modified the proxy building conditions to only build up to 2 barracks in proxy.
