### ISSUE TITLE
Expansion taken by the opponent is considered as ours

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#751]
Happened against a human in the latest patch.
![image](https://user-images.githubusercontent.com/5833235/74889194-30d45e00-534e-11ea-92a0-d79d43c3d9b9.png)

**Comment by Unusual229** [comment]
Fixed. We were just validating we owned the base and it had a valid depot (not the player owning it).
