### ISSUE TITLE
Some tiles are not part of base locations when they should be

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#782]
In this example on DiscoBloodbathLE, the Probe is on a tile that is not part of the base location, so our workers won't try to defend.
![image](https://user-images.githubusercontent.com/5833235/77257307-d2024d00-6c49-11ea-8419-89052fe4e89a.png)

**Comment by Unusual229** [comment]
Mixed up with another issue. Not fixed yet.
