### ISSUE TITLE
We should not blindly produce Hellions against Zerg

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#827]
In this case, we scout a few lings with a Roach Warren and a Nydus Canal. We should have produced Cyclones and Marauders, not Hellions and a Starport.
![image](https://user-images.githubusercontent.com/5833235/78416209-5ca55d80-75f5-11ea-9795-290869020f86.png)

**Comment by Unusual229** [comment]
Sure, but the best solution is to prevent the nydus from ever starting. We need a viking patrolling the map (mainly near our base) to make sure there is no overlord nearby.
