### ISSUE TITLE
Worker tried building a Refinery with less than 75 minerals

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#847]
We should not consider resource collection rate to decide when to send a worker to the build location if we have very few workers.
![image](https://user-images.githubusercontent.com/5833235/79163849-d5eb4000-7dad-11ea-96c4-2199f06fb502.png)

**Comment by Unusual229** [comment]
Ah, yeah seems logical.
Should be easy to fix.

**Comment by Unusual229** [comment]
Preventing the bot from considering the mineral income rate if we have 3 or less mineral workers (25% of the starting workers).
If you agree this is fine, I'll push the fix and close the issue.

**Comment by RaphaelRoyerRivard** [comment]
Yeah that seems fine
