### ISSUE TITLE
No expansion was built in the entire game (worker stuck)

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#855]
Probably happened because we had a worker stucked.
![image](https://user-images.githubusercontent.com/5833235/79350593-a8190f00-7f05-11ea-88a5-a9752a930e38.png)

**Comment by RaphaelRoyerRivard** [comment]
Happened again, but that time for the 5th base.
![image](https://user-images.githubusercontent.com/5833235/79468774-5a67d980-7fcd-11ea-92cd-6a235da93a59.png)

**Comment by Unusual229** [comment]
Not an easy fix...
We can either add reserved tiles around all the buildings (we can get stuck the same way with an armory).
We can also detect the stuck worker. In which case we have a few options:
- Lift buildings to unstuck it, doesn't work for armory and such.
- Lift the worker with a medivac.
- Kill the worker with a ranged/air unit.

I propose to do the detection of the issue. You could do the micro to lift/kill the worker.

**Comment by RaphaelRoyerRivard** [comment]
Yeah I could do some micro to kill it. But most importantly if we know the worker is stuck, we should filter it out of the potential builders.

**Comment by Unusual229** [comment]
Shouldnt happen anymore.
