### ISSUE TITLE
Starport never built a Techlab to produce Banshees

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#864]
https://ai-arena.net/matches/201139/
![image](https://user-images.githubusercontent.com/5833235/79687873-3ea44380-8218-11ea-850a-007d655cdee3.png)

**Comment by RaphaelRoyerRivard** [comment]
Later in the game, a Reactor was built on this Starport and a Techlab was built on another one to produce BCs.

**Comment by RaphaelRoyerRivard** [comment]
I really can't see how this is possible by looking through the code. I guess we should have something that periodically print into our logs what is in our production queue and what is currently in production.

**Comment by Unusual229** [comment]
I assume we just never had the resources. Without more information, not much can be done. Update this is it happens again please.
