### ISSUE TITLE
Make sure to build a refinery against worker rush

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#907]
At the moment, if the enemy workers arrive too soon, we won't build the refinery.

**Comment by Unusual229** [comment]
Why? The builder goes to fight? We don't have the mineral?

**Comment by RaphaelRoyerRivard** [comment]
In the last game we lost vs the worker rush bot, we made a proxy Barracks but the enemy workers arrived at our base before we had enough minerals for a refinery. Atm, we prevent the construction of refineries while worker rushed so we never made one and thus only made Marines which died to the workers.
