### ISSUE TITLE
Skip the production of upgrades if we are early rushed unless it is an important one

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#916]
We could allow only the Banshee Cloak and Concussive Shells while skipping the others.

**Comment by Unusual229** [comment]
Why those two? Which upgrades will be skipped?

**Comment by RaphaelRoyerRivard** [comment]
The ones that are long and expensive like the Cyclone damage upgrade, blue
flame, Banshee speed and Stimpack. Not sure yet about Yamato. Maybe we
should also skip the damage and armor upgrades?

**Comment by Unusual229** [comment]
Define early rush. I doubt we are getting yamato while earlier rushed.

**Comment by RaphaelRoyerRivard** [comment]
It previously was before 5 minutes and I changed it for 7 minutes because
the attacks of both Protoss bots we are losing to atm are done around
5:00-5:30. We usually don't research the Yamato upgrade before that moment
so it isn't very important.

**Comment by Unusual229** [comment]
Could definitely not research upgrades (wep/armor) while early rushed. Techs is more complicated since you want it to be a case by case.
