### ISSUE TITLE
We should keep our Banshee home until we have the cloak upgrade

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#917]
Against Protoss, we can easily lose it to Phoenixes and Stalkers since they move faster. Same against Terran with Cyclones. Maybe it is safe against Zerg.

**Comment by Unusual229** [comment]
Disagree, if you keep it home until you have cloak, you just missed the timing where you can do dmg.
You need to be moving towards the enemy base, but you should wait for cloak to attack.

**Comment by RaphaelRoyerRivard** [comment]
What if we meet Phoenixes in the middle of the map? This is what just
happened in our last game against TyrP.

**Comment by Unusual229** [comment]
You can have the banshees fly around the edge of the map, this will allow us to hit the mineral lines from the side of behind, reducing the chance of encoutering stalkers right away. Might slow the banshees enough to always have cloak done.
