### ISSUE TITLE
Workers generate way too many actions

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#940]
https://ai-arena.net/matches/249428/
![image](https://user-images.githubusercontent.com/5833235/83817247-3bfb9180-a692-11ea-8bfb-532d88c66301.png)

**Comment by RaphaelRoyerRivard** [comment]
In that game, we had 3 gas bunkers, which doesn't help.

**Comment by RaphaelRoyerRivard** [comment]
Maybe we could compute the statistics in the API to have a better idea of what actions are repeated too much.

**Comment by RaphaelRoyerRivard** [comment]
Around 90% of actions sent from the bot are STOP commands from the workers. According to my very brief debugging, the fact that the same workers are present multiple times in the `workerRemovedFromGas` vector might be the principal reason of the problem. Once you fixed the bug, just tell me and I'll compute the stats again to see if there are still too many actions sent.

**Comment by Unusual229** [comment]
Remove the workerRemovedFromGas variable, it was used for gas workers action spam, which shouldn't be necessary anymore.
