### ISSUE TITLE
Create a defensive build with an early PF

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#969]
BlinkerBot hits around 4:30 so we need the PF by that time.
Spiny at 3:00.
Strelok between 2:30 and 3:00.

**Comment by RaphaelRoyerRivard** [comment]
Our current FAST_PF build is `Supply Depot, CC, Barracks, 2 Refineries, Supply Depot, Orbital Command, Engineering Bay, PF` and the PF is finished by 3:20.
We make the 2 other Refineries right after we start the PF and this makes us float gas like crazy because our Factory is delayed by the PF. Also, we have close to no units during a long period and our Barracks is idle for the most part. Finally, since we have no few production buildings and a lot of resources, we make a third by 4:20 which is very greedy.
We probably could wait for the Factory to finish before taking the 2 Refineries in the natural and produce Marines or Marauders out of the Barracks. That way we might get an army strong enough to defend against any push and it could naturally delay our third.

**Comment by Unusual229** [comment]
I have no problem with delaying the refineries. But before we try and do any chances in that direction. I'd like to know the exact state of our resources when the refineries are started (minerals, gas and number of gas workers in the refineries).

**Comment by RaphaelRoyerRivard** [comment]
We have around 150 minerals and 50 gas to spare when we start the PF (we start the Refineries right after). 3 gas worker per Refinery.
The reason we have mineral and gas is because the Engineering bay is delayed by the fact that we wait for the Orbital Command to start but we produce a worker right before the Barracks finishes so we have to wait like 10 seconds for it to finish so we can start the Orbital Command.
