### ISSUE TITLE
Thor is dancing instead of attacking

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#971]
https://ai-arena.net/matches/274558/
![image](https://user-images.githubusercontent.com/5833235/86966931-e7877e00-c137-11ea-9124-1f714697d22c.png)

The problem seems to come from those lines, which are supposed to be queued actions...
![image](https://user-images.githubusercontent.com/5833235/86967387-92983780-c138-11ea-88d9-7dd4b34f3d3d.png)
maybe there is some call where the wrong method definition is used and target pointer is converted to a bool and interpreted as a queued action...

**Comment by RaphaelRoyerRivard** [comment]
The reason is because the Thor is standing on top of a supply depot that we are trying to raise.

**Comment by Unusual229** [comment]
Fixed. However, because I fixed it, we may end up losing games because one of our units is blocking the depot from being raised.

**Comment by RaphaelRoyerRivard** [comment]
The code shouldn't need to loop through all of our units since we already do that right before. That code also have a check for flying units. That distance check with radius should be move inside that code.
