### ISSUE TITLE
Allow builder premovement for first expand of FAST_PF strategy

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#981]
That would allow us to get our Barracks, Orbital and PF like 5 seconds sooner.

**Comment by Unusual229** [comment]
So you want the premovement to check if we will have the requirements to build the building when we will arrive at the target location?

**Comment by Unusual229** [comment]
Ah no. The issue is that the premovement is not allowed for expansions?
There is code specificly added to prevent it (!data.isResourceDepot), no reason to prevent it is specified, I could reenable it.

**Comment by Unusual229** [comment]
ProductionManager::347

**Comment by RaphaelRoyerRivard** [comment]
We should have added the comment "To prevent workers to over produce new expansions beause they would start it as soon as we have like 280 minerals".
But maybe the logic for creating new expansions is better, although it is probably safer to not remove that condition. We should ignore that condition only when we really want the expansion as soon as possible, i.e. only in the FAST_PF build.

**Comment by Unusual229** [comment]
As discussed, a flag will be added that will allow us to set it when we want to expand as fast as possible (while still producing units). It will be set by default for the first expand of the FAST_PF build.
This flag could be used when we take a good engagement and we are even or lower on expand than our opponent is.
